defaultTheme = "auto"
fingerprint = "md5"
dateFormat = "2006-01-02"
enablePWA = false

[author]
  name = "yanyin1986"
  email = "yanyin1986@gmail.com"
  link = "https://github.com/yanyin1986"

[image]
  # 缓存图片链接到本地
  cacheRemote = true
  # 图片缩放和优化
  optimise = true

[section]
  # section 页面每页显示文章数量
  paginate = 20
  # 日期格式 (月和日)
  dateFormat = "01-02"
  # RSS 文章数目
  rss = 10
  # 最近更新文章设置
  [section.recentlyUpdated]
    enable = true
    rss = true
    days = 30
    maxCount = 10

# List (目录或标签) 页面配置
[list]
  # list 页面每页显示文章数量
  paginate = 20
  # 日期格式 (月和日)
  dateFormat = "01-02"
  # RSS 文章数目
  rss = 10

# 文章页面配置
[page]
  # 是否在主页隐藏一篇文章
  hiddenFromHomePage = false
  # 是否在搜索结果中隐藏一篇文章
  hiddenFromSearch = false
  # 是否使用 twemoji
  twemoji = false
  # 是否使用 lightgallery
  lightgallery = false
  # 是否使用 ruby 扩展语法
  ruby = true
  # 是否使用 fraction 扩展语法
  fraction = true

  # 是否显示原始 Markdown 文档内容的链接
  linkToMarkdown = true
  # 配置文章原始文件的链接
  linkToSource = "https://github.com/yanyin1986/yanyin1986.github.io/tree/main/content/{path}"
  # 配置编辑文章的链接
  linkToEdit = "https://github.com/yanyin1986/yanyin1986.github.io/edit/main/content/{path}"
  # 配置提交错误的链接
  # linkToReport = "https://github.com/HEIGE-PCloud/DoIt/issues/new?title=[bug]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|Url|{url}|%0A|Filename|https://github.com/HEIGE-PCloud/DoIt/blob/main/exampleSite/content/{path}|"
  # 是否在 RSS 中显示全文内容
  rssFullText = false
  # 是否使用系列导航
  seriesNavigation = true
  # 是否启用最后修改时间
  enableLastMod = true
  # 是否启用字数统计
  enableWordCount = true
  # 是否启用阅读时间估计
  enableReadingTime = true
  # 在文章开头显示提示信息，提醒读者文章内容可能过时。
  [page.instantpage]
    enable = true
  # 目录配置
  [page.toc]
    # 是否使用目录
    enable = true
    # 是否保持使用文章前面的静态目录
    keepStatic = false
    # 是否使侧边目录自动折叠展开
    auto = true
  # 代码配置
  [page.code]
    # 默认展开显示的代码行数
    maxShownLines = 10
    # 是否显示代码行号
    lineNos = true
    # 是否开启代码换行
    wrap = false
    # 是否显示代码块标题
    header = true
  # 表格配置
  [page.table]
    # 是否开启表格排序
    sort = true
  [page.header]
    # 是否开启标题自动编号
    [page.header.number]
      enable = true
      [page.header.number.format]
        h2 = "{h2} {title}"
        h3 = "{h2}.{h3} {title}"
        h4 = "{h2}.{h3}.{h4} {title}"
        h5 = "{h2}.{h3}.{h4}.{h5} {title}"
        h6 = "{h2}.{h3}.{h4}.{h5}.{h6} {title}"
  # KaTeX 数学公式配置 (KaTeX https://katex.org/)
  [page.math]
    enable = false
    # 默认块定界符是 $$ ... $$ 和 \\[ ... \\]
    blockLeftDelimiter = ""
    blockRightDelimiter = ""
    # 默认行内定界符是 $ ... $ 和 \\( ... \\)
    inlineLeftDelimiter = ""
    inlineRightDelimiter = ""
    # KaTeX 插件 copy_tex
    copyTex = true
    # KaTeX 插件 mhchem
    mhchem = true
    # 使用 MathJax 替代 KaTeX
    mathjax = false
  # 文章页面的分享信息设置
  [page.share]
    enable = true
    Baidu = false
    Blogger = false
    Buffer = false
    Digg = false
    Evernote = false
    Facebook = false
    Flipboard = false
    HackerNews = true
    Instapaper = false
    Line = false
    Linkedin = false
    Mix = false
    Myspace = false
    Odnoklassniki = false
    Pinterest = false
    Pocket = false
    Reddit = false
    Renren = false
    Skype = false
    Stumbleupon = false
    Telegram = true
    Trello = false
    Tumblr = false
    Twitter = true
    VK = false
    Weibo = true
    # Weixin API example: "https://tenapi.cn/qr/?txt="
    # https://docs.tenapi.cn/qrcode.html
    # https://www.free-api.com/doc/531
    # http://www.alapi.cn/api/view/72
    # OR self-hosted: https://github.com/yhf7952/QrCodeApi
    Weixin = ""
    Whatsapp = false
    Xing = false
    Mastodon = true
  # 第三方库配置
  [page.library]
    [page.library.css]
      # someCSS = "some.css"
      # [page.library.css.someOtherCSS]
      #   src = "someOther.css"
      #   defer = true
      #   attr = "customAttribute"
      # located in "assets/" 位于 "assets/"
      # Or 或者
      # someCSS = "https://cdn.example.com/some.css"
    [page.library.js]
      # someJavaScript = "some.js"
      # [page.library.js.someOtherJavaScript]
      #   src = "someOther.js"
      #   defer = false
      #   async = true
      #   attr = "customAttribute"
      # located in "assets/" 位于 "assets/"
      # Or 或者
      # someJavascript = "https://cdn.example.com/some.js"
  # Page SEO config
  # 页面 SEO 配置
  [page.seo]
    # image URL
    # 图片 URL
    images = []
    # Publisher info
    # 出版者信息
    [page.seo.publisher]
      name = "xxxx"
      logoUrl = "/images/avatar.webp"
  # Related content config
  # 相关文章推荐配置
  [page.related]
    enable = true
    count = 5