---
title: Leon.yan
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: yanyin1986@gmail.com
description: write the code
baseurl: ''
url: ''
twitter_username: yanyin1986
github_username: yanyin1986
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-compose
