name: Hugo command

on:
  workflow_dispatch:
    inputs:
      article_title:
        description: 'article title'
        required: true
        type: string
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    if:  ${{ inputs.article_title }} 
    env:
      HUGO_VERSION: 0.114.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PAT }}
      - name: New post markdown
        run: |
          hugo new posts/${{ inputs.article_title }}.md
      - name: Add new article 
        run: |
          git status
          git config --global user.email "yanyin1986@gmail.com"
          git config --global user.name "Leon.yan"
          git add . 
          git commit -m "Add new article"
          git push

